<template>
  <div style="margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 10px; color: #94a3b8; display: flex; justify-content: space-between;">
    <span>Generated by BlindSpot Disaster Resilience Platform</span>
    <span>Page 1 of 8</span>
  </div>
</template>

<script setup lang="ts">
// No props required; static content for now
</script>